<?xml version="1.0"?>
<robot name="laser_turret" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Constants for robot dimensions -->
	<xacro:property name="PI" value="3.1415926535897931"/>
	<xacro:property name="mass" value="10000"/>
	<xacro:property name="mass2" value="1"/>
	<xacro:property name="laser_mass" value="1"/>
	<xacro:property name="length" value="4.0"/>
	<xacro:property name="width" value="2.0"/>
	<xacro:property name="height" value="3.8"/>
	<xacro:property name="offset" value="0.4"/>
	<xacro:property name="radius" value="0.2"/>
	<!--	Including gazebo file	-->
	<xacro:include filename="$(find raksha)/urdf/servo.gazebo" />


  	<link name="servo1">
  		<collision>
  			<origin xyz="0 0 0" rpy="0 0 0"/>
  			<geometry>
  				<box size="${length} ${width} ${height}"/>
  			</geometry>
  		</collision>
  		<visual>
  			<origin xyz="0 0 0" rpy="0 0 0"/>
  			<geometry>
  				<box size="${length} ${width} ${height}"/>
  			</geometry>
  		</visual>
  		<inertial>
  			<origin xyz="0 0 0" rpy="0 0 0"/>
  			<mass value="${mass}"/>
  			<inertia
  				ixx="${mass/12.0*(height*height+width*width)}" ixy="0.0" ixz="0.0" iyy="${mass/12.0*(height*height+length*length)}" iyz="0.0" izz="${mass/12.0*(length*length+width*width)}"/>
  		</inertial>
  	</link>

  	<link name="servo2">
  		<collision>
  			<origin xyz="0 0 0" rpy="${PI*0.5} 0 0"/>
  			<geometry>
  				<box size="${length} ${width} ${height}"/>
  			</geometry>
  		</collision>
  		<visual>
  			<origin xyz="0 0 0" rpy="${PI*0.5} 0 0"/>
  			<geometry>
  				<box size="${length} ${width} ${height}"/>
  			</geometry>
  		</visual>
  		<inertial>
  			<origin xyz="0 0 0" rpy="${PI*0.5} 0 0"/>
  			<mass value="${mass2}"/>
  			<inertia
  				ixx="${mass2/12.0*(height*height+width*width)}" ixy="0.0" ixz="0.0" iyy="${mass2/12.0*(height*height+length*length)}" iyz="0.0" izz="${mass2/12.0*(length*length+width*width)}"/>
  		</inertial>
  	</link>

  	<joint name="joint1" type="continuous">
  		<parent link="servo1"/>
  		<child link="servo2"/>
  		<origin xyz="${length*0.25} 0 ${height-width*(0.5)+offset}" rpy="0 0 0"/>
  		<axis xyz="0 0 1"/>
  		<dynamics damping="0.7"/>
  	</joint>

  	<link name="laser">
  		<collision>
  			<origin xyz="0 0 0" rpy="0 0 0"/>
  			<geometry>
  				<cylinder radius="${radius}" length="${length*0.5}"/>
  			</geometry>
  		</collision>
  		<visual>
  			<origin xyz="0 0 0" rpy="0 0 0"/>
  			<geometry>
  				<cylinder radius="${radius}" length="${length*0.5}"/>
  			</geometry>
  		</visual>
  		<inertial>
  			<origin xyz="0 0 0" rpy="0 0 0"/>
  			<mass value="${laser_mass}"/>
  			<inertia ixx="${laser_mass/48*length*length+laser_mass/4*radius*radius}" ixy="0.0" ixz="0.0" iyy="${laser_mass/48*length*length+laser_mass/4*radius*radius}" iyz="0.0"
  				izz="${laser_mass/2*radius*radius}"/>
  		</inertial>
  	</link>

  	<joint name="joint2" type="continuous">
  		<parent link="servo2"/>
  		<child link="laser"/>
  		<origin xyz="${length*0.5} ${-(length*0.5+offset)} 0" rpy="0 ${PI*0.5} 0"/>
  		<axis xyz="0 1 0"/>
  		<dynamics damping="0.7"/>
  	</joint>

  	<transmission name="tran1">
  		<type>transmission_interface/SimpleTransmission</type>
  		<joint name="joint1">
  			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  		</joint>
  		<actuator name="motor1">
  			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  			<mechanicalReduction>1</mechanicalReduction>
  		</actuator>
  	</transmission>

  	<transmission name="tran2">
  		<type>transmission_interface/SimpleTransmission</type>
  		<joint name="joint2">
  			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  		</joint>
  		<actuator name="motor2">
  			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  			<mechanicalReduction>1</mechanicalReduction>
  		</actuator>
  	</transmission>
</robot>
